kind: AppProject
metadata:
  name: kaiburr-prod
  namespace: argocd
spec:
  description: dev-project
  sourceRepos:
  - '*'

  destinations:
  - namespace: prod-ns
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
