apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/AASAITHAMBI57/kaiburr_CD.git
  password: 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
  username: AASAITHAMBI57
