apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kaiburr-prod
  namespace: argocd
spec: 
  destination:
    namespace: prod-ns
    server: "https://kubernetes.default.svc"
  project: kaiburr-prod
  source: 
    path: kustomize-yaml/prod-env
    repoURL: https://github.com/AASAITHAMBI57/kaiburr_CD.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:   
      prune: true  
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
