apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: prodenvdeploy
  namespace: prod-ns
spec:                
  selector:         
    matchLabels:
      app: prod
  replicas: 5      
  template:
    metadata:
      labels:        
        app: prod
    spec:
      containers:
        - name: prodenvcontainer
          image: aasaithambi5/kaiburr:2.0.0-19
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 8080                
          env:   
          - name: DB_HOST   
            valueFrom: 
              configMapKeyRef:
                name: db-conf-prod  
                key: host
          - name: DB_NAME  
            valueFrom:
              configMapKeyRef:
                name: db-conf-prod 
                key: name
          - name: DB_USERNAME  
            valueFrom:
              secretKeyRef:
                name: db-credentials-prod 
                key: username
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: db-credentials-prod
                key: password 
