apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: prodenvdeploy
  namespace: prod-ns
spec:                
  selector:         
    matchLabels:
      app: prod
  replicas: 2       
  template:
    metadata:
      labels:        
        app: prod
    spec:
      containers:
        - name: prodenvcontainer
          image: aasaithambi5/kaiburr:1.0.0-17
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 8080
