apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: kaiburr:kaiburr-14
  namespace: prod-ns
spec:                
  selector:         
    matchLabels:
      app: prodkaiburr:kaiburr-14
  replicas: 2       
  template:
    metadata:
      labels:        
        app: prodkaiburr:kaiburr-14
    spec:
      containers:
        - name: prodkaiburr:kaiburr-14
          image: aasaithambi5/back-end-app:1
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 8080
