apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: devenvdeploy
  namespace: dev-ns
spec:                
  selector:         
    matchLabels:
      app: dev
  replicas: 2       
  template:
    metadata:
      labels:        
        app: dev
    spec:
      containers:
        - name: devenvcontainer
          image: aasaithambi5/dev-kaiburr:2.0.0-5
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 8080                
          env:   
          - name: DB_HOST   
            valueFrom: 
              configMapKeyRef:
                name: db-conf-dev 
                key: host
          - name: DB_NAME  
            valueFrom:
              configMapKeyRef:
                name: db-conf-dev
                key: name
          - name: DB_USERNAME  
            valueFrom:
              secretKeyRef:
                name: db-credentials-dev
                key: username
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: db-credentials-dev
                key: password 
